export const STATUS = {
  NOT_STARTED: 'not_started',
  IN_PROGRESS: 'in_progress',
  DONE: 'done',
  REVIEW: 'review',
  SKIPPED: 'skipped',
};

export const STATUS_CONFIG = {
  not_started: { label: 'To Do', color: '#64748b', bg: 'rgba(100,116,139,0.12)', border: 'rgba(100,116,139,0.3)', icon: '○' },
  in_progress: { label: 'In Progress', color: '#fbbf24', bg: 'rgba(251,191,36,0.12)', border: 'rgba(251,191,36,0.35)', icon: '◑' },
  done: { label: 'Done', color: '#34d399', bg: 'rgba(52,211,153,0.12)', border: 'rgba(52,211,153,0.35)', icon: '●' },
  review: { label: 'Needs Review', color: '#f72585', bg: 'rgba(247,37,133,0.12)', border: 'rgba(247,37,133,0.35)', icon: '◈' },
  skipped: { label: 'Skip for Now', color: '#7209b7', bg: 'rgba(114,9,183,0.12)', border: 'rgba(114,9,183,0.3)', icon: '⊘' },
};

export const DIFFICULTY = {
  EASY: { label: 'Foundation', color: '#34d399', bg: 'rgba(52,211,153,0.12)' },
  MEDIUM: { label: 'Intermediate', color: '#fbbf24', bg: 'rgba(251,191,36,0.12)' },
  HARD: { label: 'Advanced', color: '#f87171', bg: 'rgba(248,113,113,0.12)' },
};

export const SECTIONS = [
  {
    id: 'dsa',
    num: '01',
    title: 'Data Structures & Algorithms',
    icon: '⚡',
    accent: '#00f5d4',
    topics: [
      {
        id: 'arrays',
        icon: '🧮',
        title: 'Arrays & Strings',
        difficulty: 'EASY',
        desc: 'The bread and butter. Master these first — every interview has them.',
        accent: '#00f5d4',
        subtopics: [
          'Two Pointer Technique', 'Sliding Window', 'Prefix Sum', 'Kadane\'s Algorithm',
          'Boyer-Moore Voting', 'Dutch National Flag', 'Anagram Detection', 'Rotation Problems',
          'Matrix Traversal', 'String Hashing', 'KMP Algorithm', 'Z Algorithm',
          'Rabin-Karp', 'In-place Operations', 'Merge Intervals', 'Subarray Problems',
          'Monotonic Stack', 'Trapping Rain Water', 'Next Greater Element',
        ],
        resources: ['LeetCode Array Problems', 'NeetCode Array Playlist'],
        leetcodeCount: 80,
        weeks: '1–2',
      },
      {
        id: 'linked-list',
        icon: '🔗',
        title: 'Linked Lists',
        difficulty: 'EASY',
        desc: 'Pointer manipulation and in-place reversal — classic interview staple.',
        accent: '#4361ee',
        subtopics: [
          'Singly Linked List', 'Doubly Linked List', 'Fast & Slow Pointers', 'Reversal Techniques',
          'Merge Sorted Lists', 'Floyd\'s Cycle Detection', 'LRU Cache', 'LFU Cache',
          'Skip Lists', 'Palindrome Check', 'Intersection Point', 'K-th from End',
          'Flatten Lists', 'Copy with Random Pointer',
        ],
        resources: ['CLRS Chapter 10', 'LeetCode Linked List Tag'],
        leetcodeCount: 35,
        weeks: '3',
      },
      {
        id: 'trees',
        icon: '🌳',
        title: 'Trees & Binary Trees',
        difficulty: 'MEDIUM',
        desc: 'Hierarchical data, traversals, and recursive problem solving.',
        accent: '#f72585',
        subtopics: [
          'DFS Pre/In/Post Order', 'BFS / Level Order', 'BST Operations', 'BST Properties',
          'AVL Trees', 'Red-Black Trees', 'Lowest Common Ancestor', 'Segment Trees',
          'Fenwick Tree (BIT)', 'Trie (Prefix Tree)', 'Suffix Tree', 'N-ary Trees',
          'Diameter of Tree', 'Tree Serialization', 'Morris Traversal', 'Path Sum Problems',
          'Height Balancing', 'Binary Lifting',
        ],
        resources: ['NeetCode Tree Playlist', 'Striver\'s Tree Series'],
        leetcodeCount: 55,
        weeks: '4–5',
      },
      {
        id: 'graphs',
        icon: '🕸️',
        title: 'Graphs',
        difficulty: 'HARD',
        desc: 'The hardest category. Master this = master FAANG.',
        accent: '#7209b7',
        subtopics: [
          'BFS on Graphs', 'DFS on Graphs', 'Topological Sort (Kahn\'s)', 'Topological Sort (DFS)',
          'Dijkstra\'s Algorithm', 'Bellman-Ford', 'Floyd-Warshall', 'A* Algorithm',
          'Union-Find (DSU)', 'Prim\'s MST', 'Kruskal\'s MST', 'Cycle Detection',
          'Bipartite Check', 'SCC (Kosaraju)', 'Tarjan\'s Algorithm', 'Network Flow',
          'Graph Coloring', 'Bridges & Articulation Points', 'Eulerian Path',
        ],
        resources: ['William Fiset Graph Course', 'CP-Algorithms', 'Striver Graph Series'],
        leetcodeCount: 60,
        weeks: '6–8',
      },
      {
        id: 'dp',
        icon: '⚡',
        title: 'Dynamic Programming',
        difficulty: 'HARD',
        desc: 'The holy grail. Most feared, most rewarding to master.',
        accent: '#fbbf24',
        subtopics: [
          '1D DP (Fibonacci, Coins)', '2D DP (Grid, LCS)', 'Knapsack 0/1', 'Unbounded Knapsack',
          'Longest Common Subsequence', 'Longest Increasing Subsequence', 'Edit Distance',
          'Bitmask DP', 'Memoization', 'Tabulation', 'Space Optimization', 'Interval DP',
          'Tree DP', 'Digit DP', 'Probability DP', 'Stock Buy-Sell (6 variants)',
          'Partition DP', 'DP on Strings', 'Matrix Chain Multiplication',
        ],
        resources: ['Aditya Verma DP Playlist', 'NeetCode DP', 'Striver DP Series'],
        leetcodeCount: 70,
        weeks: '9–12',
      },
      {
        id: 'heaps',
        icon: '📊',
        title: 'Heaps, Stacks & Queues',
        difficulty: 'MEDIUM',
        desc: 'Essential for scheduling, ordering, and streaming problems.',
        accent: '#34d399',
        subtopics: [
          'Min Heap', 'Max Heap', 'Priority Queue', 'Monotonic Stack', 'Monotonic Queue',
          'K-th Largest/Smallest', 'Top-K Elements Pattern', 'Heap Sort',
          'Merge K Sorted Lists', 'Two Heaps Pattern', 'Sliding Window Max',
          'Task Scheduler', 'Lazy Deletion', 'Deque Problems', 'Expression Evaluation',
        ],
        resources: ['LeetCode Heap Tag', 'Educative Heap Pattern'],
        leetcodeCount: 30,
        weeks: '13',
      },
      {
        id: 'sorting',
        icon: '🔃',
        title: 'Sorting & Searching',
        difficulty: 'EASY',
        desc: 'Binary search is a must. Know every sorting algorithm cold.',
        accent: '#4361ee',
        subtopics: [
          'Binary Search (Classic)', 'Binary Search on Answer', 'Rotated Array Search',
          'Merge Sort', 'Quick Sort', 'Counting Sort', 'Radix Sort', 'Bucket Sort',
          'Quick Select', 'External Sort', 'Search in 2D Matrix', 'Ternary Search',
        ],
        resources: ['LeetCode Binary Search Tag', 'CLRS Sorting Chapters'],
        leetcodeCount: 40,
        weeks: '14',
      },
      {
        id: 'backtracking',
        icon: '🔄',
        title: 'Backtracking & Recursion',
        difficulty: 'MEDIUM',
        desc: 'Generate all combinations, permutations, subsets — prune with intelligence.',
        accent: '#f72585',
        subtopics: [
          'N-Queens Problem', 'Sudoku Solver', 'Permutations', 'Combinations', 'Subsets',
          'Word Search', 'Letter Combinations Phone', 'Palindrome Partitioning',
          'Combination Sum Variants', 'Rat in a Maze', 'Knight\'s Tour',
        ],
        resources: ['NeetCode Backtracking', 'Striver Recursion Series'],
        leetcodeCount: 25,
        weeks: '15',
      },
    ],
  },
  {
    id: 'system-design',
    num: '02',
    title: 'System Design',
    icon: '🏗️',
    accent: '#4361ee',
    topics: [
      {
        id: 'distributed',
        icon: '☁️',
        title: 'Distributed Systems',
        difficulty: 'HARD',
        desc: 'Scale from 1 to 1 billion users — understanding trade-offs at every layer.',
        accent: '#00f5d4',
        subtopics: [
          'CAP Theorem', 'PACELC Theorem', 'Consistency Models (Eventual, Strong, Causal)',
          'Replication (Leader-Follower, Multi-Master)', 'Partitioning & Sharding',
          'Consistent Hashing', 'Raft Consensus', 'Paxos Consensus',
          'Vector Clocks', 'Gossip Protocol', 'Bloom Filters', 'Leader Election',
          'Two-Phase Commit', 'SAGA Pattern', 'Event Sourcing', 'CQRS',
        ],
        resources: ['DDIA Book', 'Martin Kleppmann Lectures', 'MIT 6.824'],
        leetcodeCount: 0,
        weeks: '16–17',
      },
      {
        id: 'databases',
        icon: '🗄️',
        title: 'Databases & Storage',
        difficulty: 'HARD',
        desc: 'SQL vs NoSQL, indexing strategies, and query optimization at scale.',
        accent: '#f72585',
        subtopics: [
          'RDBMS (PostgreSQL, MySQL)', 'MongoDB', 'Cassandra', 'DynamoDB', 'Redis',
          'B-Tree Indexing', 'LSM Tree', 'Inverted Indexes', 'ACID Properties',
          'BASE Properties', 'Query Optimization', 'EXPLAIN Plans', 'Column Stores',
          'Time-Series Databases', 'Graph Databases', 'Write-Ahead Log', 'MVCC',
          'Connection Pooling', 'Read Replicas', 'Database Sharding',
        ],
        resources: ['DDIA Chapter 3', 'CMU Database Course', 'Use The Index Luke'],
        leetcodeCount: 0,
        weeks: '17',
      },
      {
        id: 'designs',
        icon: '⚙️',
        title: 'Classic System Designs',
        difficulty: 'HARD',
        desc: 'The canonical questions asked at every FAANG interview.',
        accent: '#4361ee',
        subtopics: [
          'URL Shortener (TinyURL)', 'Rate Limiter', 'Twitter Feed (News Feed)',
          'Instagram / Photo Upload', 'WhatsApp / Chat System', 'YouTube / Netflix',
          'Uber / Lyft (Ride Sharing)', 'Google Drive / Dropbox', 'Web Crawler',
          'Search Engine (Typeahead)', 'Notification System', 'Payment System',
          'Recommendation Engine', 'Ad Click Aggregator', 'Distributed Cache',
          'Distributed Job Scheduler', 'Pastebin', 'Ticket Master (High Demand Events)',
        ],
        resources: ['Grokking System Design', 'ByteByteGo Book', 'System Design Primer (GitHub)'],
        leetcodeCount: 0,
        weeks: '18–19',
      },
      {
        id: 'infra',
        icon: '🌐',
        title: 'Infrastructure & Networking',
        difficulty: 'MEDIUM',
        desc: 'Load balancers, CDNs, caching — the connective tissue of modern systems.',
        accent: '#7209b7',
        subtopics: [
          'Load Balancing L4 vs L7', 'CDN Architecture', 'Redis / Memcached Caching',
          'Cache Eviction Policies (LRU, LFU, TTL)', 'Kafka Message Queue', 'RabbitMQ',
          'API Gateway', 'Reverse Proxy (Nginx)', 'HTTP/1.1 vs HTTP/2 vs HTTP/3',
          'WebSockets & SSE', 'DNS Resolution', 'TCP vs UDP', 'TLS/SSL Handshake',
          'Circuit Breaker Pattern', 'Service Mesh (Istio)', 'gRPC vs REST vs GraphQL',
        ],
        resources: ['CS75 Harvard Scalability Lecture', 'High Scalability Blog'],
        leetcodeCount: 0,
        weeks: '19',
      },
    ],
  },
  {
    id: 'cs-fundamentals',
    num: '03',
    title: 'CS Fundamentals',
    icon: '💻',
    accent: '#f72585',
    topics: [
      {
        id: 'os',
        icon: '🖥️',
        title: 'Operating Systems',
        difficulty: 'MEDIUM',
        desc: 'Processes, threads, memory — the OS is everywhere in backend interviews.',
        accent: '#34d399',
        subtopics: [
          'Process vs Thread vs Coroutine', 'CPU Scheduling (FCFS, SJF, Round Robin)',
          'Memory Management', 'Paging & Segmentation', 'Deadlocks (Conditions, Prevention)',
          'Mutex & Semaphores', 'Virtual Memory', 'TLB & Page Tables', 'Context Switching',
          'File Systems (ext4, NTFS)', 'I/O Scheduling', 'Cache Coherence',
          'Kernel vs User Mode', 'System Calls', 'Copy-on-Write', 'NUMA Architecture',
        ],
        resources: ['OSTEP (Free Book)', 'Galvin OS Book', 'Linux Kernel Docs'],
        leetcodeCount: 0,
        weeks: '20',
      },
      {
        id: 'concurrency',
        icon: '🔒',
        title: 'Concurrency & Multithreading',
        difficulty: 'HARD',
        desc: 'Write correct parallel code — critical for performance engineering roles.',
        accent: '#f72585',
        subtopics: [
          'Race Conditions', 'Data Races', 'Locks & Spinlocks', 'Read-Write Locks',
          'Lock-free Data Structures', 'Thread Pools', 'Task Queues', 'async/await',
          'Event Loops', 'Producer-Consumer Problem', 'Dining Philosophers',
          'Monitor Pattern', 'Futures & Promises', 'Actor Model', 'Memory Barriers',
          'Compare-and-Swap (CAS)', 'Reactive Streams',
        ],
        resources: ['Java Concurrency in Practice', 'The Little Book of Semaphores'],
        leetcodeCount: 15,
        weeks: '20',
      },
      {
        id: 'networks',
        icon: '🌍',
        title: 'Computer Networks',
        difficulty: 'EASY',
        desc: 'From TCP/IP to HTTP/3 — how data moves across the internet.',
        accent: '#00f5d4',
        subtopics: [
          'OSI Model (7 Layers)', 'TCP Three-Way Handshake', 'TCP Congestion Control',
          'HTTP 1.0 / 1.1 / 2 / 3', 'HTTPS & TLS', 'DNS Lookup Process',
          'DHCP & ARP', 'REST API Design', 'GraphQL', 'gRPC', 'WebSockets',
          'Long Polling vs SSE', 'CORS & Security Headers', 'Subnetting & CIDR',
          'BGP & Routing Protocols', 'NAT & Firewalls',
        ],
        resources: ['Computer Networking: A Top-Down Approach', 'Beej\'s Guide to Networking'],
        leetcodeCount: 0,
        weeks: '20',
      },
      {
        id: 'oops',
        icon: '🎨',
        title: 'OOP & Design Patterns',
        difficulty: 'MEDIUM',
        desc: 'Low-level design interview staple — model the real world in code.',
        accent: '#4361ee',
        subtopics: [
          'SOLID Principles', 'DRY, KISS, YAGNI', 'Singleton Pattern', 'Factory Pattern',
          'Abstract Factory', 'Builder Pattern', 'Observer Pattern', 'Strategy Pattern',
          'Decorator Pattern', 'Adapter Pattern', 'Command Pattern', 'Iterator Pattern',
          'MVC / MVP / MVVM', 'Dependency Injection', 'Inversion of Control',
          'Low Level Design: Parking Lot', 'Low Level Design: Chess', 'Low Level Design: Library',
        ],
        resources: ['Refactoring Guru', 'Head First Design Patterns', 'Clean Code (Book)'],
        leetcodeCount: 0,
        weeks: '21',
      },
    ],
  },
  {
    id: 'behavioral',
    num: '04',
    title: 'Behavioral & Leadership',
    icon: '🎯',
    accent: '#fbbf24',
    topics: [
      {
        id: 'amazon-lp',
        icon: '📋',
        title: 'Amazon Leadership Principles',
        difficulty: 'EASY',
        desc: 'Prepare 2–3 STAR stories per principle. Non-negotiable for Amazon & AWS.',
        accent: '#fbbf24',
        subtopics: [
          'Customer Obsession', 'Ownership', 'Invent and Simplify', 'Are Right, A Lot',
          'Learn and Be Curious', 'Hire and Develop the Best', 'Insist on Highest Standards',
          'Think Big', 'Bias for Action', 'Frugality', 'Earn Trust',
          'Dive Deep', 'Have Backbone — Disagree and Commit', 'Deliver Results',
          'Strive to be Earth\'s Best Employer', 'Success and Scale Bring Broad Responsibility',
        ],
        resources: ['Amazon Leadership Principles Page', 'Interview Kickstart Behavioral'],
        leetcodeCount: 0,
        weeks: '22',
      },
      {
        id: 'star',
        icon: '⭐',
        title: 'STAR Method & Story Bank',
        difficulty: 'EASY',
        desc: 'Build a bank of 15+ power stories. Every story should have impact numbers.',
        accent: '#34d399',
        subtopics: [
          'Situation — Setting Context', 'Task — Your Responsibility', 'Action — What YOU did',
          'Result — Quantified Outcomes', 'Conflict Resolution Story', 'Leadership Example',
          'Failure & Learning Story', 'Technical Decision Story', 'Mentorship Story',
          'Cross-team Collaboration', 'Ambiguity Handling', 'High Impact Story',
          'Most Proud Of Story', 'Biggest Challenge Story', 'Innovation Story',
        ],
        resources: ['STAR Method Guide', 'Jeff H. Sipe Behavioral YouTube'],
        leetcodeCount: 0,
        weeks: '22',
      },
    ],
  },
];

export const TIMELINE = [
  { week: 'Week 01–02', title: 'Foundation — Arrays, Strings, Hashmaps', desc: 'Solve 60 easy problems. Two Pointer, Sliding Window, Prefix Sum. Build pattern-recognition muscle.', color: '#00f5d4' },
  { week: 'Week 03', title: 'Linked Lists, Stacks, Queues', desc: 'Implement LRU Cache from scratch. Practice monotonic stack problems daily.', color: '#4361ee' },
  { week: 'Week 04–05', title: 'Trees & Binary Search', desc: 'Master all traversals. Tries, Segment Trees. 50+ tree problems.', color: '#f72585' },
  { week: 'Week 06–08', title: 'Graphs — BFS, DFS, Shortest Path', desc: 'Dijkstra, Union-Find, Topological Sort. Where most candidates fail — invest heavily.', color: '#7209b7' },
  { week: 'Week 09–12', title: 'Dynamic Programming — Deep Dive', desc: '50 DP problems. 1D → 2D → Advanced patterns. This takes the most time.', color: '#fbbf24' },
  { week: 'Week 13–15', title: 'Heaps, Sorting, Backtracking', desc: 'Complete remaining DSA topics. Begin mock coding sessions with a timer.', color: '#34d399' },
  { week: 'Week 16–19', title: 'System Design Fundamentals', desc: 'Read DDIA. Design URL shortener, Twitter, WhatsApp, YouTube weekly.', color: '#00f5d4' },
  { week: 'Week 20–21', title: 'CS Fundamentals + Low-Level Design', desc: 'OS, Networks, Databases, Design Patterns. Daily mock interviews begin.', color: '#4361ee' },
  { week: 'Week 22', title: 'Behavioral — STAR Stories', desc: 'Prepare 15 STAR stories. Research target companies. Record yourself.', color: '#f72585' },
  { week: 'Week 23–24', title: 'Full Mock Interviews & Final Polish', desc: 'Daily mocks. Patch weak spots. Apply broadly. Trust the process.', color: '#fbbf24' },
];
